### ISSUE TITLE
How to parse tuple like label arrays?

### ISSUE THREAD

**Issue by Dentrax** [dtolnay/serde-yaml#130]
Hey,

I am new in Rust.  I have a file that I couldn't parse for hours. Like that struct:

```
hosts:
  - foo: "Hi"
    bar: "Hey"

  - foo: "Hi"
    bar: "Hey"
```

What kind of structure should I build to deserialize this `yaml` file correctly? 
Thank you!

**Comment by dtolnay** [comment]
The 'hosts' field looks like a vec of structs.

```rust
use serde::Deserialize;

#[derive(Deserialize, Debug)]
struct Doc {
    hosts: Vec<Host>,
}

#[derive(Deserialize, Debug)]
struct Host {
    foo: String,
    bar: String,
}

const Y: &str = r#"
hosts:
  - foo: "Hi"
    bar: "Hey"

  - foo: "Hi"
    bar: "Hey"
"#;

fn main() -> serde_yaml::Result<()> {
    let doc: Doc = serde_yaml::from_str(Y)?;
    println!("{:#?}", doc);
    Ok(())
}
```

**Comment by Dentrax** [comment]
@dtolnay Thank you!

And lastly, How can I de-serialize for non-required labels? Like `foo` is required, but `bar` and `baz` not;

```
hosts:
  - foo: "Hi"
    bar: "Hey"

  - foo: "Hi"
  - foo: "Hello"
  - foo: "Hola"
    baz: "Salut"
```

Currently, when i run the code, it panicked at run-time:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("missing field `bar`", Some(Pos { marker: Marker { index: 190, line: 13, col: 7 }, path: "hosts[1]" }))', src/libcore/result.rs:997:5`
