### ISSUE TITLE
Support tags on sequences and mappings

### ISSUE THREAD

**Issue by ExpHP** [dtolnay/serde-yaml#147]
See https://users.rust-lang.org/t/help-using-serde-yaml-to-deserialize-value-with-very-many-possible-types/37058

```rust
#[derive(Debug, Deserialize)]
enum Parameter {
    vec2(ArrayVec<[f32; 2]>),
    vec3(ArrayVec<[f32; 3]>),
    vec4(ArrayVec<[f32; 4]>),
    curve(Vec<CurveVal>),
    str32(String),
    str64(String),
    str256(String),
    string(String),
}
```

Currently, this enum type is capable of using tags in place of singleton mappings to disambiguate between its String variants:

```yaml
- !str32 "hello"
- !string "world"
```

But it cannot use tags for the sequence-type variants: (it can only use singleton mappings)

```yaml
# These don't work
- !vec3 [1.0, 0.5, 0.3]
- !curve [1.0, 0.5, 0.3]

# Required workaround
- vec3: [1.0, 0.5, 0.3]
- curve: [1.0, 0.5, 0.3]
```

A solution to this would appear to be blocked on https://github.com/chyh1990/yaml-rust/issues/147, as the upstream parsing library currently does not emit tags in its `SequenceStart` or `MappingStart` events.

---

**Aside:** I find it rather amusing how both of these issues ended up being number 147. 😄
