### ISSUE TITLE
YAML Merge key << not supported

### ISSUE THREAD

**Issue by tarquin-the-brave** [dtolnay/serde-yaml#163]
Issue seen in version `0.8.12`

[YAML Merge Key][merge] `<<` is read as a String and merge is not performed.

code:

```rust
fn main() {
    let untyped = serde_yaml::from_reader::<std::io::Stdin, serde_yaml::Value>(std::io::stdin());

    println!("\nuntyped YAML read as:");
    println!("{:?}", untyped);
}
```

Running with: 

Yaml with the merge key, `<<`:

```yaml
.town_anchor: &town { town: greenbow }
name: brian
age: 42
other:
  << : *town
  some: field
```

Yaml with merge key in explicit form: `!!merge '<<'`:

```yaml
.town_anchor: &town { town: greenbow }
name: brian
age: 42
other:
  !!merge '<<' : *town
  some: field
```

Result in:

```
$ cat data-with-merge.yaml | cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/serde_yaml_anchors`

untyped read as:
Ok(Mapping(Mapping { map: {
    String(".town_anchor"): Mapping(Mapping { map: {
        String("town"): String("greenbow")
    } }), 
    String("name"): String("brian"), 
    String("age"): Number(PosInt(42)), 
    String("other"): Mapping(Mapping { map: {
        String("<<"): Mapping(Mapping { map: {
            String("town"): String("greenbow")
        } }), 
        String("some"): String("field")
    } })
} }))
```

```
$ cat data-with-merge-explicit.yaml | cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/serde_yaml_anchors`

untyped read as:
Ok(Mapping(Mapping { map: {
    String(".town_anchor"): Mapping(Mapping { map: {
        String("town"): String("greenbow")
    } }), 
    String("name"): String("brian"), 
    String("age"): Number(PosInt(42)), 
    String("other"): Mapping(Mapping { map: {
        String("<<"): Mapping(Mapping { map: {
            String("town"): String("greenbow")
        } }), 
        String("some"): String("field")
    } })
} }))
```

(I've tried to indent that to be more readable).

So it looks like the anchors are respected but not the [merge key][merge].

[merge]: https://yaml.org/type/merge.html
