### ISSUE TITLE
Deserializing either single mapping or sequence of mappings as a single sequence

### ISSUE THREAD

**Issue by anweiss** [dtolnay/serde-yaml#166]
I've been going around in circles trying to figure this one out. I'd like to deserialize the following yaml both in the same way:

```yaml
actions:
 - create:
     a: "a"
     b: "b"
```

and

```yaml
actions:
 - create:
     - a: "a"
       b: "b"
     - a: "a"
       b: "b"
```

to

```rust
#[derive(Deserialize)]
struct Obj {
    actions: Vec<Action>,
}

#[derive(Deserialize)]
#[serde(rename_all = "lowercase"]
enum Action {
  Create(Create),
}

#[derive(Deserialize)]
struct Create {
  #[serde(flatten)]
  #[serde(deserialize_with = "my_custom_fn")]
  values: Vec<CreateValue>,
}

struct CreateValue {
  a: String,
  b: String,
}
```

When implementing a custom deserializer, the `visit_map` function works for the single mapping case, but throws an `invalid type: sequence, expected struct CreateValue` error when attempting to parse the sequence; even though I've implemented `visit_seq` it never seems to detect the sequence. Not sure how I should ultimately wire this up.
