### ISSUE TITLE
Parsing a file with anchors gives a missing field error

### ISSUE THREAD

**Issue by mrosenc** [dtolnay/serde-yaml#202]
I have this code:

```
#[derive(Debug, Deserialize)]
pub struct AllEnvironments {
  production: Option<Settings>,
  development: Option<Settings>,
  test: Option<Settings>,
}

#[derive(Debug, Deserialize)]
pub struct Settings {
  #[serde(deserialize_with = "deserialize_url")]
  pub http_api_internal: Url,
  pub api_secret: String,
}
```

and

```
let all: AllEnvironments = serde_yaml::from_reader(reader)?;
```

If I give the yaml file:

```
development: &defaults
  http_api_internal: http://localhost
  api_secret: foobar
  extra_stuff: whatever
test:
  <<: *defaults
  foo: bar
```

I get an unexpected error: `test: missing field `http_api_internal` at line 6 column 5`

Do I need to turn on some option to make anchors work?  Or are they not supported?
