### ISSUE TITLE
[Q&A] YAML deserialzation to struct

### ISSUE THREAD

**Issue by hanusek** [dtolnay/serde-yaml#203]
Hello.
I have YAML:
```yaml
size: 4
sub_types:
  - FRAME_TYPE_RESERVE_1:
    value: 0
    description: Reserve
```
I would like convert the YAML to the struct **FrameField**.
How to get **FRAME_TYPE_RESERVE_1** text?

```
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct FrameField
{
    name: String, // for example: FRAME_TYPE_RESERVE_1, FRAME_TYPE_TIME_SYNC
    size: u32,
    sub_types: Vec<FrameValue>
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct FrameValue
{
    value: u32,
    description: String,
}

How to do it?
```
**Playground:**
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7bfda2b33eea33fe8a582b38b47655c6
