### ISSUE TITLE
Random order if deserialized into a HashMap

### ISSUE THREAD

**Issue by madelaney** [dtolnay/serde-yaml#232]
With `serde-yaml` version `0.8`, when I try to deserialize as hashmap the keys are Deserialized in an inconsistent manner.

For example:

given the yaml:
```yaml
items:
  sample_item1:
    key: example_value_one
  sample_item2:
    key: example_value_two
  sample_item3:
    key: example_value_three
```

When I deserialize the aforementioned structure, if I iterate over the keys of `items` (`sample_item1`, `sample_item2`, `sample_item3`). The ordering of said items is not consistent.

I would expect the order of the keys in `items` to match the order of the data in the YAML file in a consistent manner.

- Mike D.
