### ISSUE TITLE
Supporting YAML references (anchors and aliases)

### ISSUE THREAD

**Issue by milesj** [dtolnay/serde-yaml#245]
I can't seem to get these to work, although `yaml-rust` looks to support them upstream. Given the following code:

```yaml
tasks:
    build: &webpack_shared
        command: webpack
        args: build
        inputs:
            - 'src/**/*'
    start:
        <<: *webpack_shared
        args: start
```

I'd expect `tasks.start` to inherit `command` and `inputs`, with `args` being overridden. However, both `command` and `inputs` are `None` once deserialized.

It also seems like anchors assigned at the top-level to fake fields are also not supported.

```yaml
_webpack_shared: &webpack_shared
    command: webpack
    inputs:
        - 'src/**/*'

tasks:
    build:
        <<: *webpack_shared
        args: build
    start:
        <<: *webpack_shared
        args: start
```

Has anyone actually gotten these to work?
