### ISSUE TITLE
Support for serializing flow sequences

### ISSUE THREAD

**Issue by cadubentzen** [dtolnay/serde-yaml#303]
It would be amazing to be able to serialize [flow sequences](https://yaml.org/spec/1.2.2/#741-flow-sequences), especially for Vec<u8>, as I'm trying to use serde-yaml to serialize some 64-byte sequences in a compact format.

Would a PR for this be welcome, and any ideas on how to signal that via the API?

**Comment by anthrotype** [comment]
yes, that would be nice to have in serde-yaml! In Python's PyYAML there's a `default_flow_style` option which controls whether to output dicts/sequences always in block (False) or flow (True) style, or, most usefully, if set to `None` value, it outputs flow style only for the collections that consists only of scalars, e.g.:

```yaml
    contours:
    - - x: 222.0
        y: -227.0
        typ: Line
      - x: 329.0
        y: -227.0
        typ: Line
      - x: 329.0
        y: 757.0
        typ: Line
      - x: 222.0
        y: 757.0
        typ: Line
```

... would be serialized like this with `default_flow_style=None` in PyYAML:

```yaml
    contours:
    - - {typ: Line, x: 222.0, y: -227.0}
      - {typ: Line, x: 329.0, y: -227.0}
      - {typ: Line, x: 329.0, y: 757.0}
      - {typ: Line, x: 222.0, y: 757.0}
```

Is there interest in adding support for something like this in serde_yaml?

**Comment by goertzenator** [comment]
Yes please!  Here's some output I generated today... not ideal.

```
- - - - -150
      - -150
    - - -150
      - -150
    - - -150
      - -150
    - - -150
      - -150
    - - -150
      - -150
    - - -150
      - -150
    - - -150
      - -150
    - - -150
      - -150
```

**Comment by NiceneNerd** [comment]
Similar case here, where this:
```yaml
      Vec2: !vec2
      - 1.2
      - 5.1
      Vec3: !vec3
      - 1.2
      - 5.1
      - 1.9
      Vec4: !vec4
      - 4.9
      - 1.1
      - 2.3
      - 3.5
      Color: !color
      - 0.7
      - 0.8
      - 0.9
      - 1.0
      ```
Has been more nicely represented by other tools as this:
```yaml
      Vec2: !vec2 [1.2. 5.1]
      Vec3: !vec3 [1.2, 5.1, 1.9]
      Vec4: !vec4 [4.9, 1.1, 2.3, 3.5]
      Color: !color [0.7, 0.8, 0.9, 1.0]
```
