### ISSUE TITLE
Support for references

### ISSUE THREAD

**Issue by hanusek** [dtolnay/serde-yaml#325]
Hello.
how to deserialize my YAML file with references?

**My YAML file:**
```yaml
version: 1.0
users:
  - id: &jkovalsky jkovalsky
    name: jan kovalsky
  - id: &tnovak tnovak
    name: ted novak
groups:
  - id: administrators
    users: [ *jkovalsky ]
    privileges: [ create-a-new-user, block-a-user, delete-a-user, read-content]
  - id: employees
    users: [ *tnovak ]
    privileges: [ read-content]
```

**Structs:**    
```rust
#[derive(Serialize, Deserialize, PartialEq, Debug)]
pub struct User {
    id: String,
    name: String
}

#[derive(Serialize, Deserialize, PartialEq, Debug)]
pub struct Group {
    id: String,
    users: Vec<User>,
    privileges: Vec<String>,
}

#[derive(Serialize, Deserialize, PartialEq, Debug)]
pub struct Config {
    version: String,
    users: Vec<User>,
    groups: Vec<Group>,
}
```
**Rust playground:** [click me](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f213101e91f194c8dfba9fceed365d37)
