### ISSUE TITLE
How I can read comment

### ISSUE THREAD

**Issue by guiyomh** [dtolnay/serde-yaml#332]
I have a yaml file like this:

```yaml
# document comment

# Update doc
update_frequency_sec: 120
# Thread doc
num_threads: 1
# List of data source
data_sources:
  - news.google.com
  - finance.yahoo.com
  - www.msn.com
```

I did this:

```rust
fn main() {
    let file = std::fs::File::open("config.yaml").expect("File not found !");
    let scrap_file: serde_yaml::Value = serde_yaml::from_reader(file).expect("Could not read yaml");
    println!("{:?}", scrap_file);
}

```

I want to read the comments of the file to generate documentation. But I don't find a way how to read it. 

Could you help me?
