### ISSUE TITLE
How to parse tuple struct?

### ISSUE THREAD

**Issue by duskmoon314** [dtolnay/serde-yaml#340]
I have a tuple struct `Foo(u32, u32)` as a bigger struct's field `foo: Foo`. I tried to deserialize first to know what format might be expected, and I got this:

```YAML
# Foo(7, 0)
fields:
- other_keys: values
  range:
  - 7
  - 0
```

So I tried to make the yaml in the same way.

```YAML
fields:
  - other_keys: values
    range:
      - 7
      - 0
```

But when parsing, I got this error:

```
panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: sequence, expected a map")'
```

I have no idea how to solve this. Any suggestion?
