### ISSUE TITLE
[BUG] Serialization emits invalid file with missing sections

### ISSUE THREAD

**Issue by Danvil** [dtolnay/serde-yaml#374]
I have a large application where I dump about 30 MB worth of smaller objects into a file. All objects are using serde auto-derive `[derive(Serialize, Deserialize)]`.

I am using `serde_yaml = "0.9"` and the code which writes my file looks like this:
```
let mut file = std::fs::OpenOptions::new()
  .write(true)
  .create(true)
  .open(filename)
  .context(filename.to_owned())?;
let mut out = BufWriter::new(file);
serde_yaml::to_writer(&mut out, &my_stuff).context("serialization to YAML")?;
out.flush()?;
```
(Note: I tried and it also happens without the BufWriter.)

`my_stuff` above is a large map with about 20000 objects.

Unfortunately this emits an invalid YAML file where there are obviously some pieces missing. Here is an excerpt of the file which was written:
```
    SelectionMarker:
      color:
        r: 1.0
        g: 1.0
        b: 1.0
      is_visible: true
      is_selected: false
:
      food: 30.0
      food_current: 30.0
      water: 20.0
```
There is a single line with a stray `:` and there is some data missing at that location.

So far I can say: it does seem to happen exactly once in the file and it happens towards the end of the file (this was line 1727330 of 1743267).

**Comment by dtolnay** [comment]
"Stray `:`" is not necessarily invalid YAML. You are just showing an excerpt of the file by the following is valid YAML syntax:

```yaml
?
    SelectionMarker:
      color:
        r: 1.0
        g: 1.0
        b: 1.0
      is_visible: true
      is_selected: false
:
      food: 30.0
      food_current: 30.0
      water: 20.0
```
