### ISSUE TITLE
Enhancement: Allow compact one-line representation of some fields

### ISSUE THREAD

**Issue by nyurik** [dtolnay/serde-yaml#402]
In some cases, the author may know for sure that the structure of a field will be compact enough to be representable as a one-liner:

```yaml
name: My geometries
bounds: [ -10, -23, 15, 22 ]
tags: [tag1, tag2]
```

The `bounds` field is known to always have four numbers, so it would be good to force serde to NOT serialize it like this:

```yaml
name: My geometries
bounds:
    - -10
    - -23
    - 15
    - 22
tags:
    - tag1
    - tag2
```
