### ISSUE TITLE
Yaml with colon at the beginning of a value won't parse 

### ISSUE THREAD

**Issue by joe2xyz** [dtolnay/serde-yaml#404]
Dear Serde maintainers,

Thank you for the library. It's fantastic.

When I use `serde_yaml::from_str`, the following YAML won't work:

``` yaml
- a:
    b:
      c:
        - f: [:this_WILL_fail]
        - f: [':this_will_NOT_fail']
      e:
        - { g: :this_WILL_fail }
        - { g: ':this_will_NOT_fail' }
```

But It should. You can for example try to convert it by `cat file.yml | remarshal -if yaml -of json` and `remarshal` will convert it.

Thank you.

Joe

(first I posted this in `serde-rs` https://github.com/serde-rs/serde/issues/2667 but I was asked to post it here)
